--
-- PostgreSQL database dump
--

-- Dumped from database version 17.4 (Debian 17.4-1.pgdg120+2)
-- Dumped by pg_dump version 17.4

-- Started on 2025-05-19 19:27:16

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET transaction_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

--
-- TOC entry 3365 (class 1262 OID 17405)
-- Name: todo_list; Type: DATABASE; Schema: -; Owner: postgres
--

CREATE DATABASE "todo_list" WITH TEMPLATE = template0 ENCODING = 'UTF8' LOCALE_PROVIDER = libc LOCALE = 'en_US.utf8';


ALTER DATABASE "todo_list" OWNER TO postgres;

\connect "todo_list"

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET transaction_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- TOC entry 218 (class 1259 OID 17437)
-- Name: task; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.task (
    id integer NOT NULL,
    status smallint,
    description character varying(255),
    CONSTRAINT task_status_check CHECK (((status >= 0) AND (status <= 3)))
);


ALTER TABLE public.task OWNER TO postgres;

--
-- TOC entry 217 (class 1259 OID 17436)
-- Name: task_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.task ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.task_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 3359 (class 0 OID 17437)
-- Dependencies: 218
-- Data for Name: task; Type: TABLE DATA; Schema: public; Owner: postgres
--

INSERT INTO public.task (id, status, description) VALUES (1, 1, 'aaa');
INSERT INTO public.task (id, status, description) VALUES (2, 2, 'bbb');
INSERT INTO public.task (id, status, description) VALUES (3, 0, 'ccc');
INSERT INTO public.task (id, status, description) VALUES (4, 1, 'ddd');
INSERT INTO public.task (id, status, description) VALUES (5, 2, 'eee');
INSERT INTO public.task (id, status, description) VALUES (6, 0, 'fff');
INSERT INTO public.task (id, status, description) VALUES (7, 1, 'ggg');
INSERT INTO public.task (id, status, description) VALUES (8, 2, 'hhh');
INSERT INTO public.task (id, status, description) VALUES (9, 0, 'jjj');
INSERT INTO public.task (id, status, description) VALUES (10, 1, 'kkk');
INSERT INTO public.task (id, status, description) VALUES (11, 2, 'lll');
INSERT INTO public.task (id, status, description) VALUES (12, 0, 'mmm');
INSERT INTO public.task (id, status, description) VALUES (13, 1, 'nnn');
INSERT INTO public.task (id, status, description) VALUES (14, 2, 'ooo');
INSERT INTO public.task (id, status, description) VALUES (15, 0, 'ppp');
INSERT INTO public.task (id, status, description) VALUES (16, 1, '123123123');
INSERT INTO public.task (id, status, description) VALUES (17, 0, '1131231');


--
-- TOC entry 3366 (class 0 OID 0)
-- Dependencies: 217
-- Name: task_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.task_id_seq', 20, true);


--
-- TOC entry 3212 (class 2606 OID 17442)
-- Name: task task_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.task
    ADD CONSTRAINT task_pkey PRIMARY KEY (id);


-- Completed on 2025-05-19 19:27:16

--
-- PostgreSQL database dump complete
--

